[build]
  command = "bun run build"
  publish = "dist"

  [build.environment]
    GIT_LFS_ENABLED = "true"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
